import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";
import Providers from "@/reactQuery/provider";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { ToastContainer } from "react-toastify";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["300", "400", "600", "500", "700", "900"],
  variable: "--font-urbanist",
});
export const metadata: Metadata = {
  title: "Farmer Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={urbanist.variable}>
      <body className="font-urbanist text-black bg-white">
        <ReduxProvider>
          <Providers>
            <Navbar />
            {children}
            <Footer />
          </Providers>
        </ReduxProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
